# Generated by Django 3.2.20 on 2023-08-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedecorapp', '0003_auto_20230829_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
