# Generated by Django 3.2.20 on 2023-08-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedecorapp', '0005_auto_20230829_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
