# Generated by Django 3.2.20 on 2023-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedecorapp', '0008_auto_20230830_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='HOME DECOR', max_length=200),
        ),
    ]
