# Generated by Django 3.2.20 on 2023-08-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedecorapp', '0013_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.TextField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.TextField(default='', max_length=50),
        ),
    ]
