# Generated by Django 3.2.20 on 2023-08-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homedecorapp', '0014_auto_20230830_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='homedecorapp.category'),
        ),
    ]
