# Generated by Django 3.2.20 on 2023-08-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedecorapp', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.TextField(max_length=50),
        ),
    ]
